### ISSUE TITLE
Make download async

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#212]
For example `eth/downloader.go#synchronise` method is synchronous. Refactor it to make async

**Comment by ffimnsr** [comment]
is this still an open issue?

**Comment by whilei** [comment]
Yes, but it is currently relatively low priority since there are many aspects of the downloader which are already asynchronous and the refactoring will be rather complex (as far as I can see/have experimented with so far). IMO, https://github.com/ethereumproject/go-ethereum/issues/283 would be a higher priority and more succinct task.

**Comment by ffimnsr** [comment]
@whilei okay, I'll just hop in to #245 to get to know the whole flow of geth and pinpoint the problem
