### ISSUE TITLE
Create status command

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#215]
Make it possible to use `$ geth status` to get an overview status of blockchain, including:
 - Latest blocks (fast, full, headers), and if caught up (or close?) to latest
 - chaindata db path
 - configuration specs (fork, eip/ecips in use)

... basically a comprehensive-ish++ output of chain status like what you see when you just run the geth node, but without having to run-and-quit a node.

**Comment by odeke-em** [comment]
@whilei I just got sometime right now and am wondering, without familiarity of the code base on how this would be done.

I am thinking since the idea is to get an overview of the blockchain, could it just be as simple as:
a) make a system Node
b) Start the node
c) Once the node has attempted made a connection to a server, stop it then exit

The proposed code flow will look something like:
```go
func status(ctx *cli.Context) error {
     node := MakeSystemNode(Version, ctx)
     startNode(ctx, node)
     return node.Stop()
}
```

and this borrows heavily from `func geth` with the difference being that in geth, we wait until the node exits while here we stop it after startNode returns.

**Comment by whilei** [comment]
Yes! I think that's an excellent start. I wonder if it can even be abbreviated without starting the node
```
func status(ctx *cli.Context) error {
	node := MakeSystemNode(Version, ctx)
	glog.V(logger.Info).Info(spew.Sdump(node))
	return nil
}
```
The only thing left to do is that while we get access to the `stackConf`, it doesn't look like we have clean access to [`ethConf`](https://github.com/ethereumproject/go-ethereum/blob/master/cmd/geth/flag.go#L687) yet. And I bet we can get that with a little refactoring and something like `makeEthConf`. We could also get more of a tabula rasa by graciously refactoring some of the startup configuration loggers (ie `logChainConfiguration`). Then we're off to the races!

**Comment by odeke-em** [comment]
Thanks for the feedback @whilei. My apologies for the late reply -- day job woes.

Aha interesting train of thought, I too was looking at something similar to that.
Thanks for the pointers, I've got some time tonight and I'll jump onto this.
