### ISSUE TITLE
ETC PPA

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/go-ethereum#24]

**Comment by realcodywburns** [comment]
I have azure templates, and aws cloudformations that could use a PPA to pull from. Has any progress been made on this?

**Comment by realcodywburns** [comment]
Cloud templates gave been configured to build geth from scratch . We still need pos and aur support for easy package deployment

**Comment by realcodywburns** [comment]
in progress

**Comment by ericsomdahl** [comment]
@realcodywburns cool!  Where will the build/push run at?

**Comment by realcodywburns** [comment]
it will be from canonical's ppa universe https://launchpad.net/
The ethereum-classic group is formed there for anyone needing access.

the steps to install will be 

`sudo apt-get install software-properties-common`
`sudo add-apt-repository -y ppa:ethereum-classic/etc-geth`
`sudo add-apt-repository -y ppa:ethereum-classic/etc-geth-dev`
`sudo apt-get update`
`sudo apt-get install etc-geth`

**Comment by ericsomdahl** [comment]
the PPA is being published to by the TeamCity server for both **develop** and release tags.  We are maintaining a structure parallel to what upstream is doing so @realcodywburns' description of what will happen is slightly different.

    sudo apt-get install software-properties-common
    sudo add-apt-repository -y ppa:ethereum-classic/etc-geth
    sudo apt-get update
    sudo apt-get install ethereum-classic
    # OR
    sudo apt-get install ethereum-classic-unstable

This gets you
* abigen(-unstable) Source code generator to convert Ethereum contract definitions into easy to use, compile-time type-safe Go packages.
* ethereum-classic(-unstable) Meta-package to install geth and other tools
* evm(-unstable) Developer utility version of the EVM (Ethereum Virtual Machine) that is capable of running bytecode snippets within a configurable environment and execution mode.
* geth(-unstable) Classic version of the Ethereum CLI client.
* rlpdump(-unstable) Developer utility tool that prints RLP structures.

**Comment by ericsomdahl** [comment]
ethereum-classic-unstable is currently available for install.  The first ethereum-classic build will be published when the next formal release tag is created.

**Comment by MartinMakowski** [comment]
Has there been a deployment of packages to the PPA repositories? I get the following errors at this time when following the installation steps above:

E: Unable to locate package etc-geth
E: Unable to locate package ethereum-classic
E: Unable to locate package ethereum-classic-unstable

This is the behavior as of October 22nd.

Thank you,
Martin

**Comment by ericsomdahl** [comment]
Here is the URL to the PPA.

https://launchpad.net/~ethereum-classic/+archive/ubuntu/etc-geth

What distro and version are you using?

**Comment by MartinMakowski** [comment]
I originally responded to your email from github but that doesn't appear to have correctly recognized my email response since there is no addition of my comments to this thread. I'm riposting them manually:

Hello Eric,

I am using Ubuntu Desktop 15.10 Wily Werewolf.

I have added the PPA and ran sudo apt-get update and it definitely reports that it hits the Launchpad PPA endpoints:

marty@Dionysus:~$ sudo add-apt-repository ppa:ethereum-classic/etc-geth
 Official golang implementation of the Ethereum classic protocol supporting the original chain. A version which can honestly offer both a censorship resistant and unstoppable application platform for developers.
 More info: https://launchpad.net/~ethereum-classic/+archive/ubuntu/etc-geth
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmp3pmbxs5j/secring.gpg' created
gpg: keyring `/tmp/tmp3pmbxs5j/pubring.gpg' created
gpg: requesting key E44E94CC from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp3pmbxs5j/trustdb.gpg: trustdb created
gpg: key E44E94CC: public key "Launchpad PPA for Ethereum Classic" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

When I run sudo apt-get update it correctly hits the Lauchpad endpoints:

Hit http://ppa.launchpad.net wily InRelease
Hit http://ppa.launchpad.net wily InRelease
Hit http://ppa.launchpad.net wily InRelease
Hit http://ppa.launchpad.net wily/main amd64 Packages
Hit http://archive.canonical.com wily/partner i386 Packages
Hit http://ppa.launchpad.net wily/main i386 Packages
Hit http://ppa.launchpad.net wily/main Translation-en
Hit http://ppa.launchpad.net wily/main amd64 Packages
Hit http://ppa.launchpad.net wily/main i386 Packages
Hit http://ppa.launchpad.net wily/main Translation-en
Hit http://ppa.launchpad.net wily/main amd64 Packages
Hit http://ppa.launchpad.net wily/main i386 Packages
Hit http://ppa.launchpad.net wily/main Translation-en

However once I issue the install command the package is not found, I have tried multiple package names:

marty@Dionysus:~$ sudo apt-get install ethereum-classic-unstable
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ethereum-classic-unstable

After doing some digging online I found that /etc/apt/source.list should contain the PPA after the above commands were ran. 
My Ubuntu system did not have the Ethereum Classic "deb" corresponding lines in my file so I added them manually:

## Ethereum Classic
deb http://ppa.launchpad.net/ethereum-classic/etc-geth/ubuntu wily main
deb-src http://ppa.launchpad.net/ethereum-classic/etc-geth/ubuntu wily main

Now when running apt-get update it complains about duplicate entries:
W: Duplicate sources.list entry http://ppa.launchpad.net/ethereum-classic/etc-geth/ubuntu/ wily/main amd64 Packages (/var/lib/apt/lists/ppa.launchpad.net_ethereum-classic_etc-geth_ubuntu_dists_wily_main_binary-amd64_Packages)
W: Duplicate sources.list entry http://ppa.launchpad.net/ethereum-classic/etc-geth/ubuntu/ wily/main i386 Packages (/var/lib/apt/lists/ppa.launchpad.net_ethereum-classic_etc-geth_ubuntu_dists_wily_main_binary-i386_Packages)

I think the above error establishes that indeed I already do have the PPA repository added - however the apt-get install ethereum-classic-unstable command still fails:

marty@Dionysus:~$ sudo apt-get install ethereum-classic-unstable
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ethereum-classic-unstable

I noticed on the project page that the wily build of ethereum-classic-unstable has failed - could this have anything to do with my issue? Screenshot attached:
[http://imgur.com/a/VutE2](url)

Thank you for your help, I really appreciate it.

regards,
Martin

**Comment by ericsomdahl** [comment]
@MartinMakowski Yes, thanks:  I do appreciate the comprehensive info you have provided!  But I could have stopped you at the 15.10 datum.

Wily is the issue.  The build system uses go-1.6 to build the binary packages and that version of golang is not available on Wily.  At least not through the standard channels that we can run on the Launchpad build system.

I prefer to build using the most current tools possible.  Go-1.7 is only available on Yakkety but go-1.6 is available on all of the currently-supported Ubuntu distros.  So we are using 1.6.

And there is the issue...  Wily is past [End of Life](http://fridge.ubuntu.com/2016/07/28/ubuntu-15-10-wily-werewolf-end-of-life-reached-on-july-28-2016/).  It only has go-1.5 and will not ever be updated to 1.6.  Hence the build failure.

I should remove Wily from the list of distros to attempt to build for.

**Comment by MartinMakowski** [comment]
@ericsomdahl Okay thank you for explaining the issue I will upgrade to a newer distribution that supports go-1.6. Glad to find out what the source of the problem was!

Cheers,
Martin

**Comment by ericsomdahl** [comment]
@MartinMakowski it is not a matter of your system supporting go-1.6.  The binary that is created is not dependent on having go installed at all.  If you were to point your deb source list at say the Trusty repo, you would likely be fine.  There could potentially be incorrect versions of dynamically linked libs so you would be living on the edge!

**Comment by ericsomdahl** [comment]
And as a general caution:  i would not want to run a geth node on an operating system that was not actively receiving security patches.  There seem to be no shortages of bad actors looking to exploit security flaws and running a full node exposes your IP in a very loud way.

**Comment by MartinMakowski** [comment]
Hello Eric,

I am using Ubuntu Desktop 15.10 Wily Werewolf.

I have added the PPA and ran sudo apt-get update and it definitely reports
that it hits the Launchpad PPA endpoints:

marty@Dionysus:~$ sudo add-apt-repository ppa:ethereum-classic/etc-geth
 Official golang implementation of the Ethereum classic protocol supporting
the original chain. A version which can honestly offer both a censorship
resistant and unstoppable application platform for developers.
 More info: https://launchpad.net/~ethereum-classic/+archive/ubuntu/etc-geth
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmp3pmbxs5j/secring.gpg' created
gpg: keyring `/tmp/tmp3pmbxs5j/pubring.gpg' created
gpg: requesting key E44E94CC from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp3pmbxs5j/trustdb.gpg: trustdb created
gpg: key E44E94CC: public key "Launchpad PPA for Ethereum Classic" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

When I run sudo apt-get update it correctly hits the Lauchpad endpoints:

Hit http://ppa.launchpad.net wily InRelease
Hit http://ppa.launchpad.net wily InRelease
Hit http://ppa.launchpad.net wily InRelease
Hit http://ppa.launchpad.net wily/main amd64 Packages
Hit http://archive.canonical.com wily/partner i386 Packages
Hit http://ppa.launchpad.net wily/main i386 Packages
Hit http://ppa.launchpad.net wily/main Translation-en
Hit http://ppa.launchpad.net wily/main amd64 Packages
Hit http://ppa.launchpad.net wily/main i386 Packages
Hit http://ppa.launchpad.net wily/main Translation-en
Hit http://ppa.launchpad.net wily/main amd64 Packages
Hit http://ppa.launchpad.net wily/main i386 Packages
Hit http://ppa.launchpad.net wily/main Translation-en

However once I issue the install command the package is not found, I have
tried multiple package names:

marty@Dionysus:~$ sudo apt-get install ethereum-classic-unstable
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ethereum-classic-unstable

After doing some digging online I found that /etc/apt/source.list should
contain the PPA after the above commands were ran.
My Ubuntu system did not have the Ethereum Classic "deb" corresponding
lines in my file so I added them manually:

## Ethereum Classic
deb http://ppa.launchpad.net/ethereum-classic/etc-geth/ubuntu wily main
deb-src http://ppa.launchpad.net/ethereum-classic/etc-geth/ubuntu wily main

Now when running apt-get update it complains about duplicate entries:
W: Duplicate sources.list entry
http://ppa.launchpad.net/ethereum-classic/etc-geth/ubuntu/ wily/main amd64
Packages
(/var/lib/apt/lists/ppa.launchpad.net_ethereum-classic_etc-geth_ubuntu_dists_wily_main_binary-amd64_Packages)
W: Duplicate sources.list entry
http://ppa.launchpad.net/ethereum-classic/etc-geth/ubuntu/ wily/main i386
Packages
(/var/lib/apt/lists/ppa.launchpad.net_ethereum-classic_etc-geth_ubuntu_dists_wily_main_binary-i386_Packages)

I think the above error establishes that indeed I already do have the PPA
repository added - however the apt-get install ethereum-classic-unstable
command still fails:

marty@Dionysus:~$ sudo apt-get install ethereum-classic-unstable
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ethereum-classic-unstable

I noticed on the project page that the wily build of
ethereum-classic-unstable has failed - could this have anything to do with
my issue? Screenshot attached:


​
Thank you for your help, I appreciate it.

regards,
Martin

**Comment by MartinMakowski** [comment]
Very valid concern, I'm shutting down the current geth node until I can upgrade the OS.

Thanks,
Martin

**Comment by MartinMakowski** [comment]
Living on the edge is my motto so I shall try your Trusty suggestion and report on the results. Thanks for the tip.

Cheers!
Martin

**Comment by pascaldekloe** [comment]
We dropped PPA. Installing our Go applications is simple as coping the executable to a location of your choice.
