### ISSUE TITLE
Setup Gitian building process

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/go-ethereum#338]
See https://github.com/litecoin-project/litecoin/blob/master/doc/release-process.md and https://github.com/litecoin-project/gitian.sigs.ltc for an example.

This process basically allows everyone to submit build signatures to a gitan.sigs.* repository. Users can use this repository to verify a binary. This allows other parties to join the trust process, so builds.etcdevteam.com would not be the single trust source.

@splix @whilei What's your opinions on this? If seems okay, I can help to set this up.

**Comment by whilei** [comment]
I'm OK with it. I think there's definitely a need to take steps towards an additional, easy-to-use layer of networked signatures/trust, and I really like the idea of opening that process to the public.

My only hesitation is that Litecoin's process seems... complicated, since the script/process encourages each participant to build for each system (OSX, Linux, Windows) via VM. A result of this appears that their Gitian trust networks for any given version typically include 2-4 signatures from the same users (likely devs).

I wonder if we might be able to simplify to avoid that setup overhead, lowering the "barrier to entry," and instead allowing anyone to assert a signature for a single version-build (eg. `OSX v3.5.86`). 

I wonder also if we might be able to make use of the existing https://github.com/ethereumproject/volunteer/tree/master/Volunteer-Public-Keys (or some near-variant).
