### ISSUE TITLE
How to prevent replay attacks

### ISSUE THREAD

**Issue by mi2zha** [ethereumproject/go-ethereum#362]
eth and etc's address and private key in my system are the same, how to prevent replay attacks

**Comment by splix** [comment]
@mi2zha you have to use a client or node implementation that supports EIP-155 (Replay Protection). It was implemented in most clients (Geth ETC, Geth ETH, Parity, MEW, Emerald, etc) since last year so unless you don't use something very custom and outdated you should be fine.

Geth Classic supports EIP-155
