### ISSUE TITLE
Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered

### ISSUE THREAD

**Issue by lanmp** [ethereumproject/go-ethereum#613]
2018-06-01 15:48:31 Starting server...
E0601 15:48:32.422292 p2p/nat/nat.go:114] Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
2018-06-01 15:48:32 UDP listening. Client enode: enode://f59ec567b75ab8f0c1b3cdd088dab604c691294413c1709d46e541d91570a68e484adfee1edea75e33588d18db759d870290854703f6bc3f052aa328c0161db5@[::]:30303
E0601 15:48:32.442854 p2p/nat/nat.go:114] Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
2018-06-01 15:48:32 IPC endpoint opened: /root/.ethereum-classic/mainnet/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/source/linux/go1.10.2

The version >4.1.1
Cannot sync block

**Comment by whilei** [comment]
Hey @lanmp -- the reason you can't sync is because you're on geth `4.1.1`, which is incompatible with [the planned hardfork at block 5900000](https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1041.md) that happened this past week. You'll need to upgrade to [at least Geth 5+](https://github.com/ethereumproject/go-ethereum/releases/tag/v5.4.0).

As for the UPnP "error" -- not to worry, this is actually a harmless log. I've got PR #611 in already to relegate the severity as to not be so alarming.
