### ISSUE TITLE
The return value of eth.getBlock, without mixHash field, results in false missing mixHash in JSON block header

### ISSUE THREAD

**Issue by kilvn** [ethereumproject/go-ethereum#640]
I use ETC's Ethereum Classic Geth 5.4.1 client
Encountered this problem https://github.com/ethereum/go-ethereum/issues/3230

The return value of eth.getBlock, without mixHash field, results in false missing mixHash in JSON block header

Excuse me, why does ETC's geth lose this mixHash field? I need it very much, thank you.

我用ETC的 Ethereum Classic Geth 5.4.1 客户端
遇到了这个问题   https://github.com/ethereum/go-ethereum/issues/3230

eth.getBlock 的返回值，没有  mixHash 字段，导致报错 missing mixHash in JSON block header

请问，ETC的geth为什么会少这个mixHash字段呢？我很需要它，谢谢

**Comment by whilei** [comment]
@kilvn I'm about to submit a PR to fix this issue.

Just noting for reference that all related docs on this are outdated/wrong

- https://wiki.parity.io/JSONRPC-eth-module#eth_getblockbyhash
- https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash 

and there is some confusion because of that

- https://github.com/paritytech/parity/issues/8841
-
